language: node_js
node_js:
 - 11.6.0
cache: npm

notifications:
  slack: stampede-production:JBtLOLYw1Hoq2VIl1ZiQFxWC

jobs:
include:
  - stage: "Compile"
    name: "Compile"
    install: npm install
  - stage: "Tests"                
    name: "Unit Tests"           
    script: npm test
  - stage: build
    name: "Build"
    script: npm run build