language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t oslawdev/cv -f Dockerfile .

script:
  - docker run -e CI=true oslawdev/cv npm run test

after_success:
  - docker build -t oslawdev/cv .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push oslawdev/cv