language: node_js
node_js:
 - 11.6.0
cache: npm

notifications:
  slack:
    on_success: always
    
jobs:
  include:
    - stage: test
      script: npm run test
    - stage: build
      script: npm run build