language: node_js
node_js:
 - 11.6.0
cache: npm
jobs:
  include:
    - stage: compile
      name: "Compile"
      install: npm install
    - stage: tests                
      name: "Unit Tests"           
      script: npm test
      after_success: curl -X POST -H 'Content-type: application/json' --data '{"text":"Unit test finished!"}' https://hooks.slack.com/services/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
    - stage: build
      name: "Build"
      script: npm run build
      after_success: curl -X POST -H 'Content-type: application/json' --data '{"text":" `%{repository_slug}` *%{result}* Build finished  on branch `%{branch}`!"}' https://hooks.slack.com/services/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